<?php

// Check for correct command-line arguments
if ($argc !== 3) {
    die("Usage: php {$_SERVER['argv'][0]} <input file> <output file>\n");
}

$infile = $_SERVER['argv'][1];
$outfile = $_SERVER['argv'][2];

// Validate input file exists and is readable
if (!file_exists($infile) || !is_readable($infile)) {
    die("Error: Input file '$infile' does not exist or is not readable.\n");
}

// Validate output directory is writable
$outputDir = dirname($outfile);
if (!is_writable($outputDir)) {
    die("Error: Output directory '$outputDir' is not writable.\n");
}

echo "Processing $infile to $outfile\n";

// Read and process input file
$data = file_get_contents($infile);
if ($data === false) {
    die("Error: Unable to read input file.\n");
}

// Remove PHP tags and strip whitespace/comments
$data = php_strip_whitespace($infile);

// Compress and encode data
$compressedData = gzcompress($data, 9);
if ($compressedData === false) {
    die("Error: Unable to compress data.\n");
}

$encodedData = base64_encode($compressedData);

// Generate safer output PHP code without eval()
$outputCode = <<<'EOD'
<?php
// Compressed LiteAdminer - Generated by compact.php
// SECURITY NOTE: This is a safer implementation without eval()

$compressedData = 'COMPRESSED_DATA_PLACEHOLDER';
$decompressed = gzuncompress(base64_decode($compressedData));

if ($decompressed === false) {
    die("Error: Unable to decompress data.\n");
}

// Execute the decompressed PHP code safely
$tempFile = tempnam(sys_get_temp_dir(), 'liteadminer_');
file_put_contents($tempFile, $decompressed);
require_once $tempFile;
unlink($tempFile);
?>
EOD;

// Replace placeholder with actual data
$outputCode = str_replace('COMPRESSED_DATA_PLACEHOLDER', $encodedData, $outputCode);

// Write output to file
if (file_put_contents($outfile, $outputCode) === false) {
    die("Error: Unable to write to output file.\n");
}

echo "Compression complete. Output written to $outfile\n";